### ISSUE TITLE
Mallet commandline determine convergence?

### ISSUE THREAD

**Issue by findgit123** [mimno/Mallet#179]
We are testing Mallet commandline and have found some diagnostics file after run.
How can we check sampling convergence? Where is the report or how to check this measure. And will you please simply interpret that measure?  
Many thanks

**Comment by mimno** [comment]
This is more of a Stack Overflow question, not a potential problem with the software.

Looking at the log likelihood number should give an indication of whether the sampler has reached a stable state. If you are concerned about finding an optimal solution, the `--num-icm-iterations` option will choose the best topic assignment for each token until no tokens change. Otherwise saving multiple states (`--output-state-interval`) and averaging over them is a good idea.

The diagnostics file is only about the quality of a model, and has no information on MCMC convergence. There are no exact answers for MCMC convergence, and many of the available heuristic methods assume that you have a small number of continuous variables. In LDA sampling we have potentially millions of categorical variables.

**Comment by findgit123** [comment]
thanks a lot
