### ISSUE TITLE
Lemmatization

### ISSUE THREAD

**Issue by ECMGit** [mimno/Mallet#192]
Hi,
I am wondering does Mallet have lemmatization when we build the pipeline?
I want to do:
services -> service
workers -> worker

**Comment by SeaCelo** [comment]
It might, but I find the results are very bad. We did a series of tests using aggressive preprocessing and gave it up.  Also makes the results more difficult to read  Not worth the cost:benefit, IMO.  The models handle these cases fine because it is statistical, not just word counts.

If you want to do it, I would implement the preprocessing in python. The code I sent you have that, commented. 

Marcelo

**Comment by SeaCelo** [comment]
Sorry, answering to the wrong person. Ignore. 

Marcelo

**Comment by mimno** [comment]
At least for English this is much harder to do well than most people expect: https://mimno.infosci.cornell.edu/papers/schofield_tacl_2016.pdf

It's often really a display issue, not a model issue. Adding stemming as a post-processing step may be more useful.
